//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2407
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2407.
// 
namespace Anetics.Medalist.SungardWS {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SunGardSoap", Namespace="http://www.penson.com/")]
    public class SunGard : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SunGard() {
            string urlSetting = System.Configuration.ConfigurationSettings.AppSettings["BankLoanSTKCTLWebService"];
            if ((urlSetting != null)) {
                this.Url = string.Concat(urlSetting, "");
            }
            else {
                this.Url = "http://ltpen-tpham.penson.com/Sungard/SunGard.asmx?wsdl";
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.penson.com/InqStockMaster", RequestNamespace="http://www.penson.com/", ResponseNamespace="http://www.penson.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InqStockMasterInfo InqStockMaster(string Parameters) {
            object[] results = this.Invoke("InqStockMaster", new object[] {
                        Parameters});
            return ((InqStockMasterInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInqStockMaster(string Parameters, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InqStockMaster", new object[] {
                        Parameters}, callback, asyncState);
        }
        
        /// <remarks/>
        public InqStockMasterInfo EndInqStockMaster(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((InqStockMasterInfo)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.penson.com/StockTransfer", RequestNamespace="http://www.penson.com/", ResponseNamespace="http://www.penson.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StockTransferInfo StockTransfer(string FromCode, string Quantity, string Security, string ToCode, string Account, string ToQuantity) {
            object[] results = this.Invoke("StockTransfer", new object[] {
                        FromCode,
                        Quantity,
                        Security,
                        ToCode,
                        Account,
                        ToQuantity});
            return ((StockTransferInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginStockTransfer(string FromCode, string Quantity, string Security, string ToCode, string Account, string ToQuantity, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("StockTransfer", new object[] {
                        FromCode,
                        Quantity,
                        Security,
                        ToCode,
                        Account,
                        ToQuantity}, callback, asyncState);
        }
        
        /// <remarks/>
        public StockTransferInfo EndStockTransfer(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((StockTransferInfo)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.penson.com/FreeStockMovement", RequestNamespace="http://www.penson.com/", ResponseNamespace="http://www.penson.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FreeStockMovementInfo FreeStockMovement(string From, string Security_Stkfre, string CashOverride, string To, string Account, string Qty, string Due) {
            object[] results = this.Invoke("FreeStockMovement", new object[] {
                        From,
                        Security_Stkfre,
                        CashOverride,
                        To,
                        Account,
                        Qty,
                        Due});
            return ((FreeStockMovementInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFreeStockMovement(string From, string Security_Stkfre, string CashOverride, string To, string Account, string Qty, string Due, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FreeStockMovement", new object[] {
                        From,
                        Security_Stkfre,
                        CashOverride,
                        To,
                        Account,
                        Qty,
                        Due}, callback, asyncState);
        }
        
        /// <remarks/>
        public FreeStockMovementInfo EndFreeStockMovement(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((FreeStockMovementInfo)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.penson.com/RegTradeInput", RequestNamespace="http://www.penson.com/", ResponseNamespace="http://www.penson.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RegTradeInputInfo RegTradeInput(
                    string BS, 
                    string Qty_Ordtri, 
                    string Sec, 
                    string Price, 
                    string Acct, 
                    string MktCap, 
                    string Fcom, 
                    string Dest, 
                    string Broker1, 
                    string Time, 
                    string TrdDate, 
                    string SpcCode, 
                    string EntrdBy, 
                    string Fees1, 
                    string Fees2, 
                    string Fees3, 
                    string Fees4, 
                    string Fees5) {
            object[] results = this.Invoke("RegTradeInput", new object[] {
                        BS,
                        Qty_Ordtri,
                        Sec,
                        Price,
                        Acct,
                        MktCap,
                        Fcom,
                        Dest,
                        Broker1,
                        Time,
                        TrdDate,
                        SpcCode,
                        EntrdBy,
                        Fees1,
                        Fees2,
                        Fees3,
                        Fees4,
                        Fees5});
            return ((RegTradeInputInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRegTradeInput(
                    string BS, 
                    string Qty_Ordtri, 
                    string Sec, 
                    string Price, 
                    string Acct, 
                    string MktCap, 
                    string Fcom, 
                    string Dest, 
                    string Broker1, 
                    string Time, 
                    string TrdDate, 
                    string SpcCode, 
                    string EntrdBy, 
                    string Fees1, 
                    string Fees2, 
                    string Fees3, 
                    string Fees4, 
                    string Fees5, 
                    System.AsyncCallback callback, 
                    object asyncState) {
            return this.BeginInvoke("RegTradeInput", new object[] {
                        BS,
                        Qty_Ordtri,
                        Sec,
                        Price,
                        Acct,
                        MktCap,
                        Fcom,
                        Dest,
                        Broker1,
                        Time,
                        TrdDate,
                        SpcCode,
                        EntrdBy,
                        Fees1,
                        Fees2,
                        Fees3,
                        Fees4,
                        Fees5}, callback, asyncState);
        }
        
        /// <remarks/>
        public RegTradeInputInfo EndRegTradeInput(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RegTradeInputInfo)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.penson.com/StockMultipleMovement", RequestNamespace="http://www.penson.com/", ResponseNamespace="http://www.penson.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StockMultipleMovementInfo StockMultipleMovement(string From, string To, string Account, string Security_STKMLT, string Qty, string DueBill, string CashOverride, string Desc) {
            object[] results = this.Invoke("StockMultipleMovement", new object[] {
                        From,
                        To,
                        Account,
                        Security_STKMLT,
                        Qty,
                        DueBill,
                        CashOverride,
                        Desc});
            return ((StockMultipleMovementInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginStockMultipleMovement(string From, string To, string Account, string Security_STKMLT, string Qty, string DueBill, string CashOverride, string Desc, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("StockMultipleMovement", new object[] {
                        From,
                        To,
                        Account,
                        Security_STKMLT,
                        Qty,
                        DueBill,
                        CashOverride,
                        Desc}, callback, asyncState);
        }
        
        /// <remarks/>
        public StockMultipleMovementInfo EndStockMultipleMovement(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((StockMultipleMovementInfo)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.penson.com/StockControlMovement", RequestNamespace="http://www.penson.com/", ResponseNamespace="http://www.penson.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StockControlMovementInfo StockControlMovement(string From, string To, string Qty, string Security_STKCTL, string IntlID, string Cot, string Description) {
            object[] results = this.Invoke("StockControlMovement", new object[] {
                        From,
                        To,
                        Qty,
                        Security_STKCTL,
                        IntlID,
                        Cot,
                        Description});
            return ((StockControlMovementInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginStockControlMovement(string From, string To, string Qty, string Security_STKCTL, string IntlID, string Cot, string Description, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("StockControlMovement", new object[] {
                        From,
                        To,
                        Qty,
                        Security_STKCTL,
                        IntlID,
                        Cot,
                        Description}, callback, asyncState);
        }
        
        /// <remarks/>
        public StockControlMovementInfo EndStockControlMovement(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((StockControlMovementInfo)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.penson.com/INQPSN", RequestNamespace="http://www.penson.com/", ResponseNamespace="http://www.penson.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public INQPSNInfo INQPSN(string AccountNumber) {
            object[] results = this.Invoke("INQPSN", new object[] {
                        AccountNumber});
            return ((INQPSNInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginINQPSN(string AccountNumber, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("INQPSN", new object[] {
                        AccountNumber}, callback, asyncState);
        }
        
        /// <remarks/>
        public INQPSNInfo EndINQPSN(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((INQPSNInfo)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.penson.com/")]
    public class InqStockMasterInfo {
        
        /// <remarks/>
        public string status;
        
        /// <remarks/>
        public string message;
        
        /// <remarks/>
        public string sessionKey;
        
        /// <remarks/>
        public string activeView;
        
        /// <remarks/>
        public CusipRetrievalMap CusipRetrieval;
        
        /// <remarks/>
        public int CusipRetrieval_RowCount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CusipRetrieval_RowMap[] CusipRetrieval_Row;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.penson.com/")]
    public class CusipRetrievalMap {
        
        /// <remarks/>
        public string TranID;
        
        /// <remarks/>
        public string Parameters;
        
        /// <remarks/>
        public string Message;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.penson.com/")]
    public class INQPSNMap {
        
        /// <remarks/>
        public string AccountNumber;
        
        /// <remarks/>
        public string CurrencyCode;
        
        /// <remarks/>
        public string AccountName;
        
        /// <remarks/>
        public string Symbol;
        
        /// <remarks/>
        public string Cusip;
        
        /// <remarks/>
        public string TradeDatePosition;
        
        /// <remarks/>
        public string TradeDateMarketValue;
        
        /// <remarks/>
        public string SettlementDatePosition;
        
        /// <remarks/>
        public string SettlementDateMarketValue;
        
        /// <remarks/>
        public string Message;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.penson.com/")]
    public class INQPSNInfo {
        
        /// <remarks/>
        public string status;
        
        /// <remarks/>
        public string message;
        
        /// <remarks/>
        public string sessionKey;
        
        /// <remarks/>
        public string activeView;
        
        /// <remarks/>
        public INQPSNMap INQPSN;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.penson.com/")]
    public class STKCTLMap {
        
        /// <remarks/>
        public string From;
        
        /// <remarks/>
        public string To;
        
        /// <remarks/>
        public string Qty;
        
        /// <remarks/>
        public string Security;
        
        /// <remarks/>
        public string IntlID;
        
        /// <remarks/>
        public string Cot;
        
        /// <remarks/>
        public string Description;
        
        /// <remarks/>
        public string Message;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.penson.com/")]
    public class StockControlMovementInfo {
        
        /// <remarks/>
        public string status;
        
        /// <remarks/>
        public string message;
        
        /// <remarks/>
        public string sessionKey;
        
        /// <remarks/>
        public string activeView;
        
        /// <remarks/>
        public STKCTLMap STKCTL;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.penson.com/")]
    public class STKMLTMap {
        
        /// <remarks/>
        public string From;
        
        /// <remarks/>
        public string To;
        
        /// <remarks/>
        public string Account;
        
        /// <remarks/>
        public string Security;
        
        /// <remarks/>
        public string Qty;
        
        /// <remarks/>
        public string DueBill;
        
        /// <remarks/>
        public string CashOverride;
        
        /// <remarks/>
        public string Desc;
        
        /// <remarks/>
        public string Message;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.penson.com/")]
    public class StockMultipleMovementInfo {
        
        /// <remarks/>
        public string status;
        
        /// <remarks/>
        public string message;
        
        /// <remarks/>
        public string sessionKey;
        
        /// <remarks/>
        public string activeView;
        
        /// <remarks/>
        public STKMLTMap STKMLT;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.penson.com/")]
    public class OrdtriMap {
        
        /// <remarks/>
        public string BS;
        
        /// <remarks/>
        public string Qty;
        
        /// <remarks/>
        public string Sec;
        
        /// <remarks/>
        public string Price;
        
        /// <remarks/>
        public string Acct;
        
        /// <remarks/>
        public string MktCap;
        
        /// <remarks/>
        public string Fcom;
        
        /// <remarks/>
        public string Dest;
        
        /// <remarks/>
        public string Broker1;
        
        /// <remarks/>
        public string Time;
        
        /// <remarks/>
        public string TrdDate;
        
        /// <remarks/>
        public string SpcCode;
        
        /// <remarks/>
        public string EntrdBy;
        
        /// <remarks/>
        public string Fees1;
        
        /// <remarks/>
        public string Fees2;
        
        /// <remarks/>
        public string Fees3;
        
        /// <remarks/>
        public string Fees4;
        
        /// <remarks/>
        public string Fees5;
        
        /// <remarks/>
        public string Message;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.penson.com/")]
    public class RegTradeInputInfo {
        
        /// <remarks/>
        public string status;
        
        /// <remarks/>
        public string message;
        
        /// <remarks/>
        public string sessionKey;
        
        /// <remarks/>
        public string activeView;
        
        /// <remarks/>
        public OrdtriMap Ordtri;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.penson.com/")]
    public class StkfreMap {
        
        /// <remarks/>
        public string From;
        
        /// <remarks/>
        public string Security;
        
        /// <remarks/>
        public string CashOverride;
        
        /// <remarks/>
        public string Message;
        
        /// <remarks/>
        public string To;
        
        /// <remarks/>
        public string Account;
        
        /// <remarks/>
        public string Qty;
        
        /// <remarks/>
        public string Due;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.penson.com/")]
    public class FreeStockMovementInfo {
        
        /// <remarks/>
        public string status;
        
        /// <remarks/>
        public string message;
        
        /// <remarks/>
        public string sessionKey;
        
        /// <remarks/>
        public string activeView;
        
        /// <remarks/>
        public StkfreMap Stkfre;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.penson.com/")]
    public class StktrnMap {
        
        /// <remarks/>
        public string FromCode;
        
        /// <remarks/>
        public string Quantity;
        
        /// <remarks/>
        public string Security;
        
        /// <remarks/>
        public string ToCode;
        
        /// <remarks/>
        public string Account;
        
        /// <remarks/>
        public string ToQuantity;
        
        /// <remarks/>
        public string MessageForTransfer;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.penson.com/")]
    public class StockTransferInfo {
        
        /// <remarks/>
        public string status;
        
        /// <remarks/>
        public string message;
        
        /// <remarks/>
        public string sessionKey;
        
        /// <remarks/>
        public string activeView;
        
        /// <remarks/>
        public StktrnMap Stktrn;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.penson.com/")]
    public class CusipRetrieval_RowMap {
        
        /// <remarks/>
        public int rowSequence;
        
        /// <remarks/>
        public string ShortName;
        
        /// <remarks/>
        public string Office;
        
        /// <remarks/>
        public string Account;
        
        /// <remarks/>
        public string Loc;
        
        /// <remarks/>
        public string TradeBalance;
        
        /// <remarks/>
        public string SettleBalance;
        
        /// <remarks/>
        public string LastActivity;
        
        /// <remarks/>
        public string Flag;
    }
}
