//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by this guidance package as part of the solution template
//
// For more information see: 
// ms-help://MS.VSCC.v90/MS.VSIPCC.v90/ms.practices.scsf.2008apr/SCSF/html/03-01-010-How_to_Create_Smart_Client_Solutions.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace StockLoan.Locates.Infrastructure.Interface.Constants
{
    /// <summary>
    /// Constants for event topic names.
    /// </summary>
    public class EventTopicNames
    {
        public const string StatusUpdate = "StatusUpdate";
        public const string ShellFormResize = "ShellFormResize";
        public const string ShellFormClosing = "ShellFormClosing";
        public const string ShellFormDeactivate = "ShellFormDeactivate";

        // Grid Events
        public const string LocatesGridError = "LocatesGridError";
        public const string LocatesGridKeyPress = "LocatesGridKeyPress";
        public const string LocatesGridMouseDown = "LocatesGridMouseDown";
        public const string LocatesGridFormatText = "LocatesGridFormatText";
        public const string LocatesGridBeforeColumnUpdate = "LocatesGridBeforeColumnUpdate";

        // ComboBox Events
        public const string TradeDateKeyPress = "TradeDateKeyPress";

        // List Events
        public const string InventoryListFormatText = "InventoryListFormatText";
        public const string InventoryListFetchRowStyle = "InventoryListFetchRowStyle";
        public const string LocateSummaryListFormatText = "LocateSummaryListFormatText";
        public const string PreBorrowGridBeforeUpdate = "PreBorrowGridBeforeUpdate";
        public const string PreBorrowGridKeyPress = "PreBorrowGridKeyPress";
        public const string PreBorrowGridFormatText = "PreBorrowGridFormatText";
        public const string PreBorrowGridBeforeColUpdate = "PreBorrowGridBeforeColUpdate";


        // PreBorrowLocates View Events

    }
}
