//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace WorldWideClient.ServicePositions {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePositions.IPositionsService")]
    public interface IPositionsService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPositionsService/BoxPositionGet", ReplyAction="http://tempuri.org/IPositionsService/BoxPositionGetResponse")]
        System.IAsyncResult BeginBoxPositionGet(string bizDate, string bookGroup, string secId, string userId, string userPassword, string functionPath, System.AsyncCallback callback, object asyncState);
        
        byte[] EndBoxPositionGet(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPositionsService/BoxPositionLookupGet", ReplyAction="http://tempuri.org/IPositionsService/BoxPositionLookupGetResponse")]
        System.IAsyncResult BeginBoxPositionLookupGet(string boxItems, string bookGroup, bool includeRates, string userId, System.AsyncCallback callback, object asyncState);
        
        byte[] EndBoxPositionLookupGet(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPositionsService/BoxSummaryDataConfigGet", ReplyAction="http://tempuri.org/IPositionsService/BoxSummaryDataConfigGetResponse")]
        System.IAsyncResult BeginBoxSummaryDataConfigGet(string bizDate, string bookGroup, bool IsOptimistic, string hairCutUser, string userId, string userPassword, string functionPath, System.AsyncCallback callback, object asyncState);
        
        byte[] EndBoxSummaryDataConfigGet(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPositionsServiceChannel : WorldWideClient.ServicePositions.IPositionsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BoxPositionGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public BoxPositionGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public byte[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BoxPositionLookupGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public BoxPositionLookupGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public byte[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BoxSummaryDataConfigGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public BoxSummaryDataConfigGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public byte[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PositionsServiceClient : System.ServiceModel.ClientBase<WorldWideClient.ServicePositions.IPositionsService>, WorldWideClient.ServicePositions.IPositionsService {
        
        private BeginOperationDelegate onBeginBoxPositionGetDelegate;
        
        private EndOperationDelegate onEndBoxPositionGetDelegate;
        
        private System.Threading.SendOrPostCallback onBoxPositionGetCompletedDelegate;
        
        private BeginOperationDelegate onBeginBoxPositionLookupGetDelegate;
        
        private EndOperationDelegate onEndBoxPositionLookupGetDelegate;
        
        private System.Threading.SendOrPostCallback onBoxPositionLookupGetCompletedDelegate;
        
        private BeginOperationDelegate onBeginBoxSummaryDataConfigGetDelegate;
        
        private EndOperationDelegate onEndBoxSummaryDataConfigGetDelegate;
        
        private System.Threading.SendOrPostCallback onBoxSummaryDataConfigGetCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public PositionsServiceClient() {
        }
        
        public PositionsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PositionsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PositionsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PositionsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<BoxPositionGetCompletedEventArgs> BoxPositionGetCompleted;
        
        public event System.EventHandler<BoxPositionLookupGetCompletedEventArgs> BoxPositionLookupGetCompleted;
        
        public event System.EventHandler<BoxSummaryDataConfigGetCompletedEventArgs> BoxSummaryDataConfigGetCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WorldWideClient.ServicePositions.IPositionsService.BeginBoxPositionGet(string bizDate, string bookGroup, string secId, string userId, string userPassword, string functionPath, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginBoxPositionGet(bizDate, bookGroup, secId, userId, userPassword, functionPath, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        byte[] WorldWideClient.ServicePositions.IPositionsService.EndBoxPositionGet(System.IAsyncResult result) {
            return base.Channel.EndBoxPositionGet(result);
        }
        
        private System.IAsyncResult OnBeginBoxPositionGet(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string bizDate = ((string)(inValues[0]));
            string bookGroup = ((string)(inValues[1]));
            string secId = ((string)(inValues[2]));
            string userId = ((string)(inValues[3]));
            string userPassword = ((string)(inValues[4]));
            string functionPath = ((string)(inValues[5]));
            return ((WorldWideClient.ServicePositions.IPositionsService)(this)).BeginBoxPositionGet(bizDate, bookGroup, secId, userId, userPassword, functionPath, callback, asyncState);
        }
        
        private object[] OnEndBoxPositionGet(System.IAsyncResult result) {
            byte[] retVal = ((WorldWideClient.ServicePositions.IPositionsService)(this)).EndBoxPositionGet(result);
            return new object[] {
                    retVal};
        }
        
        private void OnBoxPositionGetCompleted(object state) {
            if ((this.BoxPositionGetCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.BoxPositionGetCompleted(this, new BoxPositionGetCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void BoxPositionGetAsync(string bizDate, string bookGroup, string secId, string userId, string userPassword, string functionPath) {
            this.BoxPositionGetAsync(bizDate, bookGroup, secId, userId, userPassword, functionPath, null);
        }
        
        public void BoxPositionGetAsync(string bizDate, string bookGroup, string secId, string userId, string userPassword, string functionPath, object userState) {
            if ((this.onBeginBoxPositionGetDelegate == null)) {
                this.onBeginBoxPositionGetDelegate = new BeginOperationDelegate(this.OnBeginBoxPositionGet);
            }
            if ((this.onEndBoxPositionGetDelegate == null)) {
                this.onEndBoxPositionGetDelegate = new EndOperationDelegate(this.OnEndBoxPositionGet);
            }
            if ((this.onBoxPositionGetCompletedDelegate == null)) {
                this.onBoxPositionGetCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnBoxPositionGetCompleted);
            }
            base.InvokeAsync(this.onBeginBoxPositionGetDelegate, new object[] {
                        bizDate,
                        bookGroup,
                        secId,
                        userId,
                        userPassword,
                        functionPath}, this.onEndBoxPositionGetDelegate, this.onBoxPositionGetCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WorldWideClient.ServicePositions.IPositionsService.BeginBoxPositionLookupGet(string boxItems, string bookGroup, bool includeRates, string userId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginBoxPositionLookupGet(boxItems, bookGroup, includeRates, userId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        byte[] WorldWideClient.ServicePositions.IPositionsService.EndBoxPositionLookupGet(System.IAsyncResult result) {
            return base.Channel.EndBoxPositionLookupGet(result);
        }
        
        private System.IAsyncResult OnBeginBoxPositionLookupGet(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string boxItems = ((string)(inValues[0]));
            string bookGroup = ((string)(inValues[1]));
            bool includeRates = ((bool)(inValues[2]));
            string userId = ((string)(inValues[3]));
            return ((WorldWideClient.ServicePositions.IPositionsService)(this)).BeginBoxPositionLookupGet(boxItems, bookGroup, includeRates, userId, callback, asyncState);
        }
        
        private object[] OnEndBoxPositionLookupGet(System.IAsyncResult result) {
            byte[] retVal = ((WorldWideClient.ServicePositions.IPositionsService)(this)).EndBoxPositionLookupGet(result);
            return new object[] {
                    retVal};
        }
        
        private void OnBoxPositionLookupGetCompleted(object state) {
            if ((this.BoxPositionLookupGetCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.BoxPositionLookupGetCompleted(this, new BoxPositionLookupGetCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void BoxPositionLookupGetAsync(string boxItems, string bookGroup, bool includeRates, string userId) {
            this.BoxPositionLookupGetAsync(boxItems, bookGroup, includeRates, userId, null);
        }
        
        public void BoxPositionLookupGetAsync(string boxItems, string bookGroup, bool includeRates, string userId, object userState) {
            if ((this.onBeginBoxPositionLookupGetDelegate == null)) {
                this.onBeginBoxPositionLookupGetDelegate = new BeginOperationDelegate(this.OnBeginBoxPositionLookupGet);
            }
            if ((this.onEndBoxPositionLookupGetDelegate == null)) {
                this.onEndBoxPositionLookupGetDelegate = new EndOperationDelegate(this.OnEndBoxPositionLookupGet);
            }
            if ((this.onBoxPositionLookupGetCompletedDelegate == null)) {
                this.onBoxPositionLookupGetCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnBoxPositionLookupGetCompleted);
            }
            base.InvokeAsync(this.onBeginBoxPositionLookupGetDelegate, new object[] {
                        boxItems,
                        bookGroup,
                        includeRates,
                        userId}, this.onEndBoxPositionLookupGetDelegate, this.onBoxPositionLookupGetCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WorldWideClient.ServicePositions.IPositionsService.BeginBoxSummaryDataConfigGet(string bizDate, string bookGroup, bool IsOptimistic, string hairCutUser, string userId, string userPassword, string functionPath, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginBoxSummaryDataConfigGet(bizDate, bookGroup, IsOptimistic, hairCutUser, userId, userPassword, functionPath, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        byte[] WorldWideClient.ServicePositions.IPositionsService.EndBoxSummaryDataConfigGet(System.IAsyncResult result) {
            return base.Channel.EndBoxSummaryDataConfigGet(result);
        }
        
        private System.IAsyncResult OnBeginBoxSummaryDataConfigGet(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string bizDate = ((string)(inValues[0]));
            string bookGroup = ((string)(inValues[1]));
            bool IsOptimistic = ((bool)(inValues[2]));
            string hairCutUser = ((string)(inValues[3]));
            string userId = ((string)(inValues[4]));
            string userPassword = ((string)(inValues[5]));
            string functionPath = ((string)(inValues[6]));
            return ((WorldWideClient.ServicePositions.IPositionsService)(this)).BeginBoxSummaryDataConfigGet(bizDate, bookGroup, IsOptimistic, hairCutUser, userId, userPassword, functionPath, callback, asyncState);
        }
        
        private object[] OnEndBoxSummaryDataConfigGet(System.IAsyncResult result) {
            byte[] retVal = ((WorldWideClient.ServicePositions.IPositionsService)(this)).EndBoxSummaryDataConfigGet(result);
            return new object[] {
                    retVal};
        }
        
        private void OnBoxSummaryDataConfigGetCompleted(object state) {
            if ((this.BoxSummaryDataConfigGetCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.BoxSummaryDataConfigGetCompleted(this, new BoxSummaryDataConfigGetCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void BoxSummaryDataConfigGetAsync(string bizDate, string bookGroup, bool IsOptimistic, string hairCutUser, string userId, string userPassword, string functionPath) {
            this.BoxSummaryDataConfigGetAsync(bizDate, bookGroup, IsOptimistic, hairCutUser, userId, userPassword, functionPath, null);
        }
        
        public void BoxSummaryDataConfigGetAsync(string bizDate, string bookGroup, bool IsOptimistic, string hairCutUser, string userId, string userPassword, string functionPath, object userState) {
            if ((this.onBeginBoxSummaryDataConfigGetDelegate == null)) {
                this.onBeginBoxSummaryDataConfigGetDelegate = new BeginOperationDelegate(this.OnBeginBoxSummaryDataConfigGet);
            }
            if ((this.onEndBoxSummaryDataConfigGetDelegate == null)) {
                this.onEndBoxSummaryDataConfigGetDelegate = new EndOperationDelegate(this.OnEndBoxSummaryDataConfigGet);
            }
            if ((this.onBoxSummaryDataConfigGetCompletedDelegate == null)) {
                this.onBoxSummaryDataConfigGetCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnBoxSummaryDataConfigGetCompleted);
            }
            base.InvokeAsync(this.onBeginBoxSummaryDataConfigGetDelegate, new object[] {
                        bizDate,
                        bookGroup,
                        IsOptimistic,
                        hairCutUser,
                        userId,
                        userPassword,
                        functionPath}, this.onEndBoxSummaryDataConfigGetDelegate, this.onBoxSummaryDataConfigGetCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override WorldWideClient.ServicePositions.IPositionsService CreateChannel() {
            return new PositionsServiceClientChannel(this);
        }
        
        private class PositionsServiceClientChannel : ChannelBase<WorldWideClient.ServicePositions.IPositionsService>, WorldWideClient.ServicePositions.IPositionsService {
            
            public PositionsServiceClientChannel(System.ServiceModel.ClientBase<WorldWideClient.ServicePositions.IPositionsService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginBoxPositionGet(string bizDate, string bookGroup, string secId, string userId, string userPassword, string functionPath, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[6];
                _args[0] = bizDate;
                _args[1] = bookGroup;
                _args[2] = secId;
                _args[3] = userId;
                _args[4] = userPassword;
                _args[5] = functionPath;
                System.IAsyncResult _result = base.BeginInvoke("BoxPositionGet", _args, callback, asyncState);
                return _result;
            }
            
            public byte[] EndBoxPositionGet(System.IAsyncResult result) {
                object[] _args = new object[0];
                byte[] _result = ((byte[])(base.EndInvoke("BoxPositionGet", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginBoxPositionLookupGet(string boxItems, string bookGroup, bool includeRates, string userId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = boxItems;
                _args[1] = bookGroup;
                _args[2] = includeRates;
                _args[3] = userId;
                System.IAsyncResult _result = base.BeginInvoke("BoxPositionLookupGet", _args, callback, asyncState);
                return _result;
            }
            
            public byte[] EndBoxPositionLookupGet(System.IAsyncResult result) {
                object[] _args = new object[0];
                byte[] _result = ((byte[])(base.EndInvoke("BoxPositionLookupGet", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginBoxSummaryDataConfigGet(string bizDate, string bookGroup, bool IsOptimistic, string hairCutUser, string userId, string userPassword, string functionPath, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[7];
                _args[0] = bizDate;
                _args[1] = bookGroup;
                _args[2] = IsOptimistic;
                _args[3] = hairCutUser;
                _args[4] = userId;
                _args[5] = userPassword;
                _args[6] = functionPath;
                System.IAsyncResult _result = base.BeginInvoke("BoxSummaryDataConfigGet", _args, callback, asyncState);
                return _result;
            }
            
            public byte[] EndBoxSummaryDataConfigGet(System.IAsyncResult result) {
                object[] _args = new object[0];
                byte[] _result = ((byte[])(base.EndInvoke("BoxSummaryDataConfigGet", _args, result)));
                return _result;
            }
        }
    }
}
